In [ ]:
f = open("새파일.txt", "r")
lines = f.readlines()
f.close()
print(lines)

In [ ]:
f = open("새파일.txt", "r")
lines = f.readlines()
f.close()
newLines = []
for line in lines:
    newLines.append(line.replace("\n", ""))
print(newLines)

In [ ]:
f = open("새파일.txt", "r")
page = f.read()
f.close()
print(page)
lines = page.split("\n")
print(lines)

In [ ]:
f = open("새파일.txt", "a")
f.write("\n케케케")
f.close()

In [ ]:
with open("새파일.txt","a") as f: 
    f.write("\nㅎㅎㅎ")

In [ ]:
a = int(input("첫번째 숫자를 입력하세요:"))
b = int(input("두번째 숫자를 입력하세요:"))
c = a+b
print("두 수의 합은 "+str(c)+" 입니다." )

In [ ]:
def is_odd(number):
    if(number% 2 == 1):
        return True
    else:
        return False

In [ ]:
def avg_numbers(*args):
    result = 0
    for i in args:
        result += i
    return result

avg_numbers(1,2)
avg_numbers(1,2,3,4,5)

In [ ]:
input1 = int(input("첫번째 숫자를 입력하세요:"))
input2 = int(input("두번째 숫자를 입력하세요:"))

total = input1 + input2
print("두 수의 합은 %d 입니다"% total)

In [ ]:
print("you""need""python")
print("you"+"need"+"python")
print("you","need","python")
print("".join(["you","need","python"]))

In [ ]:
f1 = open("test.txt", "w")
f1.write("Life is too short")

f2 = open("test.txt", "r")
a = f2.read()
print(a)

In [ ]:
user_input = input("저장할 내용을 입력하세요:")
f = open("test.txt", "a")
f.write(user_input)
f.write("\n")
f.close()

In [ ]:
f = open("test.txt", "r")
body = f.read()
f.close()

body = body.replace("java","python")

f = open("test.txt","w")
f.write(body)
f.close()

In [ ]:
class FourCal:
    def setdata(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
aCal = FourCal()
bCal = FourCal()
aCal.setdata(4,2)
print(aCal.add())
bCal.setdata(3,8)
print(bCal.add())

In [ ]:
class FourCal:
    def __init__(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
aCal = FourCal(4,2)
bCal = FourCal(3,8)
print(aCal.add())
print(bCal.add())

In [ ]:
class FourCal:
    def __init__(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
    
class MoreFourCal(FourCal):
    def pow(self):
        result = self.first ** self.second
        return result
    
c = MoreFourCal(4,2)
d = c.pow()
print(d)

In [ ]:
class FourCal:
    def __init__(self,a,b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
    def div(self):
        result = self.first / self.second
        return result
class MoreFourCal(FourCal):
    def pow(self):
        result = self.first ** self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.0000000000000000000001
        result = self.first / self.second
        return result
c = MoreFourCal(4,0)
d = c.div()
print(d) 

In [ ]:
class MyMath:
    MyPI = 3.14
    
mm = MyMath()
print(mm.MyPI)

In [ ]:
mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI, mm2.MyPI)


In [ ]:
import mod1
print(mod1.add_mod1(3,4))
print(mod1.sub_mod1(3,4))

In [ ]:
from mod1 import add_mod1, sub_mod1
print(add_mod1(3,4))
print(sub_mod1(3,4))

In [ ]:
from mod1 import *
print(add_mod1(3,4))
print(sub_mod1(3,4))

In [ ]:
import mod1 as m1
print(m1.add_mod1(3,4))
print(m1.sub_mod1(3,4))

In [ ]:
import mod2
print(mod2.add_mod2(3,4))
print(mod2.PI)
mm2 = mod2.Math_mod2()
print(mm2.solve(2))

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
try:
    print(4/0)
except ZeroDivisionError as e:
    print(4/0.0000000000000000000000000000000001)
    #print(e)

In [ ]:
def positive(l):
    result=[]
    for i in l:
        if i > 0: result.append(i)
    return result

print(positive([1,-3,2,0,-5,6]))

In [ ]:
def positive(x):
    return x> 0 
data = [1,-3,2,0,-5,6]
f = filter(positive,data)
print(list(f))


In [ ]:
data=[1,-3,2,0,-5,6]
list(filter(lambda x: x>0, data))

In [ ]:
a = int(input("숫자를 입력하세요"))
a = a+1
print(a)

In [3]:
a,b = map(int,input("숫자 2개를 입력하세요").split())
print(a+1,"그리고",b+1)

숫자 2개를 입력하세요10 20
11 그리고 21


In [5]:
data1 = [1,2,3]
data2 = [4,5,6]
list(zip(data1,data2))

[(1, 4), (2, 5), (3, 6)]

In [7]:
import os
os.environ["path"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\W

In [8]:
os.getcwd()

'C:\\Workspace\\Python\\2021-05-26 Lecture'

In [12]:
import glob
glob.glob('C:\\Workspace\\Python\\2021-05-26 Lecture\\*.py')

['C:\\Workspace\\Python\\2021-05-26 Lecture\\mod1.py',
 'C:\\Workspace\\Python\\2021-05-26 Lecture\\mod2.py']

In [13]:
a=[1,2,3]
b = a
b

[1, 2, 3]

In [17]:
import tempfile

In [18]:
import time

In [19]:
time.time()

1622012971.5858514

In [25]:
time.asctime(time.localtime(time.time()))

'Wed May 26 16:10:49 2021'

In [26]:
time.asctime(time.localtime(time.time())).split()

['Wed', 'May', '26', '16:11:01', '2021']

In [27]:
time.ctime()

'Wed May 26 16:11:24 2021'

In [29]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [127]:
import random
random.random()

0.7235974427010342

In [642]:
random.randint(1,45)

2


In [689]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for i in range(10): my_arr2=my_arr*2

Wall time: 18 ms


In [685]:
%time for i in range(10): my_list2=[x*2 for x in my_list]

Wall time: 803 ms


In [695]:
data = np.random.randn(2,3)
data

array([[-2.15472268, -0.89956008, -0.8738174 ],
       [ 0.76150477,  0.53835956, -1.1572312 ]])

In [696]:
data * 10

array([[-21.54722676,  -8.99560084,  -8.738174  ],
       [  7.61504767,   5.38359564, -11.57231201]])

In [697]:
data+data

array([[-4.30944535, -1.79912017, -1.7476348 ],
       [ 1.52300953,  1.07671913, -2.3144624 ]])

In [698]:
data.shape

(2, 3)

In [699]:
data.dtype

dtype('float64')

In [701]:
data = [ 6,7.5,8,0,1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [703]:
data2d = [[1,2,3,4],[5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [704]:
arr2d = np.array(data2d)

In [705]:
arr2d.ndim

2

In [706]:
arr2d.shape

(2, 4)

In [708]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [709]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [710]:
np.zeros((2,3,2)).dtype

dtype('float64')

In [719]:
arr = np.zeros((2,3,2), dtype=np.int32)
arr

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [724]:
arr1 = np.zeros((2,3))
arr2 = np.ones_like(arr1)
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [726]:
arr3 = np.full((2,3),5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [735]:
arr4 = np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])